<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="Microsoft.AspNetCore.Http.Abstractions">
            <HintPath>..\..\..\..\..\..\..\..\..\usr\local\share\dotnet\shared\Microsoft.AspNetCore.App\8.0.2\Microsoft.AspNetCore.Http.Abstractions.dll</HintPath>
        </Reference>
        <Reference Include="Microsoft.Extensions.Logging.Abstractions">
            <HintPath>..\..\..\..\..\..\..\..\..\usr\local\share\dotnet\shared\Microsoft.AspNetCore.App\8.0.2\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4-beta1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Contracts\Articles.Contracts\Articles.Contracts.csproj"/>
    </ItemGroup>

</Project>
